spring:
  profiles:
    group:
      local: "testdb,common"
---
spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/batch_study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: jden
    password: jden
    pool:
      max-size: 100
      validation-query: SELECT 1
  config:
    activate:
      on-profile: local

